apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "base.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.envFrom }}
          envFrom: {{ toYaml .Values.envFrom | nindent 12 }}
           {{- end }}
          env:
          {{- range $k, $v := .Values.environmentVariables }}
            - name: {{ quote $k }}
              value: {{ quote $v }}
          {{- end }}
          {{- if .Values.service.port -}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.service.ports -}}
          ports:
            {{- toYaml .Values.service.ports | nindent 12 }}
          {{- end }}
          {{- if .Values.monitorConfig.liveness }}
          livenessProbe:
            {{ .Values.monitorConfig.liveness | toYaml | indent 12 | trim }}
          {{- end }}
          {{- if .Values.monitorConfig.readiness }}
          readinessProbe:
            {{ .Values.monitorConfig.readiness | toYaml | indent 12 | trim }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
          - name: data
            mountPath: {{ .Values.persistence.mountPath }}
            {{- if .Values.persistence.subPath }}
            subPath: {{ .Values.persistence.subPath }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "base.fullname" .) }}
      {{- end -}}
