apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  
  {{- if .Values.service.ports -}}
  ports:
    {{- toYaml .Values.service.ports | nindent 12 }}
  {{- end }}
  {{- if .Values.service.port -}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- end }}
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
